<?php

use App\Http\Controllers\V2\Catalogs\EvaluationTypeController;
use App\Http\Controllers\V2\Catalogs\MatterController;
use App\Http\Controllers\V2\Catalogs\AspectController;
use App\Http\Controllers\V2\Catalogs\ScopeController;
use App\Http\Controllers\V2\Catalogs\StatusController;
use App\Http\Controllers\V2\Catalogs\PriorityController;
use App\Http\Controllers\V2\Catalogs\CategoryController;
use App\Http\Controllers\V2\Catalogs\ConditionController;
use App\Http\Controllers\V2\Catalogs\IndustryController;
use App\Http\Controllers\V2\Catalogs\CountryController;
use App\Http\Controllers\V2\Catalogs\StateController;
use App\Http\Controllers\V2\Catalogs\CityController;
use App\Http\Controllers\V2\Catalogs\ProfileTypeController;
use App\Http\Controllers\V2\Catalogs\PeriodController;
use App\Http\Controllers\V2\ProfileController;
use App\Http\Controllers\V2\LicenseController;
use App\Http\Controllers\V2\Catalogs\ApplicationTypeController;
use App\Http\Controllers\V2\Catalogs\LegalClassificationController;
use App\Http\Controllers\V2\Catalogs\RequirementTypeController;
use App\Http\Controllers\V2\Catalogs\EvidenceController;
use App\Http\Controllers\V2\Catalogs\QuestionTypeController;
use App\Http\Controllers\V2\Catalogs\AnswerValueController;
use App\Http\Controllers\V2\Audit\AuditController;
use App\Http\Controllers\V2\Catalogs\RequirementController;
use App\Http\Controllers\V2\Catalogs\SubrequirementController;
use App\Http\Controllers\V2\CustomerController;
use App\Http\Controllers\V2\CorporateController;
use App\Http\Controllers\V2\UserController;
use App\Http\Controllers\V2\Catalogs\PeriodicityController;
use App\Http\Controllers\V2\Catalogs\FormController;
use App\Http\Controllers\V2\Catalogs\Risk\RiskCategoryController;
use App\Http\Controllers\V2\Audit\ProcessController;
use App\Http\Controllers\V2\Catalogs\GuidelineController;
use App\Http\Controllers\V2\Catalogs\Risk\RiskAttributeController;
use App\Http\Controllers\V2\Catalogs\TopicController;
use App\Http\Controllers\V2\Catalogs\QuestionController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['auth'], 'prefix' => 'v2/source'], function () {
  Route::get('matter', [MatterController::class, 'source'])->name('v2.source.matter');
  Route::get('aspect', [AspectController::class, 'source'])->name('v2.source.aspect');
  Route::get('evaluation', [EvaluationTypeController::class, 'source'])->name('v2.source.evaluation');
  Route::get('scope', [ScopeController::class, 'source'])->name('v2.source.scope');
  Route::get('status', [StatusController::class, 'source'])->name('v2.source.status');
  Route::get('priority', [PriorityController::class, 'source'])->name('v2.source.priority');
  Route::get('category', [CategoryController::class, 'source'])->name('v2.source.category');
  Route::get('condition', [ConditionController::class, 'source'])->name('v2.source.condition');
  Route::get('industry', [IndustryController::class, 'source'])->name('v2.source.industry');
  Route::get('country', [CountryController::class, 'source'])->name('v2.source.country');
  Route::get('state', [StateController::class, 'source'])->name('v2.source.state');
  Route::get('city', [CityController::class, 'source'])->name('v2.source.city');
  Route::get('profile', [ProfileController::class, 'source'])->name('v2.source.profile');
  Route::get('profile_type', [ProfileTypeController::class, 'source'])->name('v2.source.profile_type');
  Route::get('license', [LicenseController::class, 'source'])->name('v2.source.license');
  Route::get('period', [PeriodController::class, 'source'])->name('v2.source.period');
  Route::get('application_type', [ApplicationTypeController::class, 'source'])->name('v2.source.application_type');
  Route::get('application_type/specific', [ApplicationTypeController::class, 'sourceSpecific'])->name('v2.source.application_type.specific');
  Route::get('legal_classification', [LegalClassificationController::class, 'source'])->name('v2.source.legal_classification');
  Route::get('requirement_type', [RequirementTypeController::class, 'source'])->name('v2.source.requirement_type');
  Route::get('evidence', [EvidenceController::class, 'source'])->name('v2.source.evidence');
  Route::get('question_type', [QuestionTypeController::class, 'source'])->name('v2.source.question_type');
  Route::get('answer_value', [AnswerValueController::class, 'source'])->name('v2.source.answer_value');
  Route::get('audit', [AuditController::class, 'source'])->name('v2.source.audit');
  Route::get('customer', [CustomerController::class, 'source'])->name('v2.source.customer');
  Route::get('corporate', [CorporateController::class, 'source'])->name('v2.source.corporate');
  Route::get('user', [UserController::class, 'source'])->name('v2.source.user');
  Route::get('periodicity', [PeriodicityController::class, 'source'])->name('v2.source.periodicity');
  Route::get('form', [FormController::class, 'source'])->name('v2.source.form');
  Route::get('risk', [RiskCategoryController::class, 'source'])->name('v2.source.risk');
  Route::get('process', [ProcessController::class, 'source'])->name('v2.source.process');
  Route::get('risk_attribute', [RiskAttributeController::class, 'source'])->name('v2.source.risk_attribute');
  Route::get('topic', [TopicController::class, 'source'])->name('v2.source.topic');
  Route::get('guideline', [GuidelineController::class, 'source'])->name('v2.source.guideline');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'v2/source/single'], function () {
  Route::get('process/{id}', [ProcessController::class, 'single'])->name('v2.source.single.process');
  Route::get('requirement/{id}', [RequirementController::class, 'single'])->name('v2.source.single.requirement');
  Route::get('subrequirement/{id}', [SubrequirementController::class, 'single'])->name('v2.source.single.subrequirement');
  Route::get('question/{id}', [QuestionController::class, 'single'])->name('v2.source.single.question');
});