<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

include('auth/auth.php');
include('dashboard/dashboard.php');
include('admin/customers.php');
include('admin/corporates.php');
include('catalogues/locations.php');
include('catalogues/industries.php');
include('catalogues/legals.php');
include('catalogues/requirements.php');
include('catalogues/questions.php');
include('catalogues/matters.php');
include('catalogues/periods.php');
include('admin/licenses.php');
include('admin/contracts.php');
include('admin/profiles.php');
include('admin/permissions.php');
include('admin/users.php');
include('admin/account.php');
include('audit/aplicability.php');
include('audit/obligations.php');
include('audit/audit.php');
include('audit/processes.php');
include('news/news.php');
include('files/files.php');
include('comments/comments.php');
include('audit/action.php');
include('notifications/notifications.php');
include('catalogues/risks.php');
include('details/details.php');
// include('requirements/requirements.php');

include('v2/defaults.php');
include('v2/catalogs/catalogs.php');
include('v2/catalogs/forms.php');
include('v2/process.php');
include('v2/customer.php');
include('v2/corporate.php');
include('v2/obligation.php');
include('v2/profile.php');
include('v2/user.php');
include('v2/auditRegister.php');
include('v2/obligationRegister.php');
include('v2/aplicabilityRegister.php');
include('v2/catalogs/questions.php');
include('v2/catalogs/requirements.php');
include('v2/catalogs/subrequirements.php');
include('v2/actionRegister.php');
include('v2/actionPlan.php');
include('v2/tasks.php');
include('v2/library.php');
include('v2/files.php');
include('v2/comments/comments.php');
include('v2/dashboard/dashboard.php');
include('v2/catalogs/riskCategories.php');
include('v2/audit.php');
include('v2/license.php');
include('v2/contract.php');
include('v2/contact.php');
include('v2/address.php');
include('v2/image.php');
include('v2/account.php');
include('v2/notification.php');
include('v2/catalogs/industries.php');
include('v2/catalogs/matters.php');
include('v2/catalogs/aspects.php');
include('v2/catalogs/guidelines.php');
include('v2/catalogs/legalBasi.php');
include('v2/catalogs/recomendation.php');
include('v2/auditAspect.php');
include('v2/riskEvalaute.php');
include('v2/specificRequirement.php');
include('v2/catalogs/risks.php');
include('v2/new.php');
include('v2/details.php');
include('v2/knowledge.php');
include('v2/catalogs/articles.php');
include('v2/catalogs/knowledgeTopics.php');
include('v2/contractAspect.php');
include('v2/aplicability.php');
include('v2/backup.php');
